### ISSUE TITLE
Install Godot and compile/run the application on your computer

### ISSUE THREAD

**Issue by jsseng** [jsseng/jigsaw#19]
Use git to download the source code and compile using Godot.  Also, post what platform you are running on (Win/Mac/Linux).

**Comment by annahuang28** [comment]
Windows

**Comment by jsseng** [comment]
Please don't close the issue, just remove your name from the assignees list.

**Comment by Kenton227** [comment]
Linux

**Comment by yivanovaa** [comment]
Windows

**Comment by jasmiineng** [comment]
Mac

**Comment by LambNNot** [comment]
Windows

**Comment by KailuanLiu** [comment]
windows

**Comment by vhuang20** [comment]
mac

**Comment by stephenlin801** [comment]
windows
