### ISSUE TITLE
Research/develop a backend database for the puzzle application

### ISSUE THREAD

**Issue by jsseng** [jsseng/jigsaw#20]
We will need a database in order to store which pieces are placed and also keep track of statistics.

**Comment by jsseng** [comment]
Data to store in the database:  currently active puzzles, who is working on each puzzle, the placed pieces of a puzzle, when did users place a piece, when did users login/logout, which messages were sent, statistics about UI usage

**Comment by LambNNot** [comment]
https://heroiclabs.com/blog/godot-fishgame/

**Comment by LambNNot** [comment]
https://silentwolf.com

**Comment by jsseng** [comment]
Here is a Godot Firebase plugin:  https://github.com/GodotNuts/GodotFirebase

**Comment by KailuanLiu** [comment]
![firebase1](https://github.com/jsseng/jigsaw/assets/156022154/2a09e247-11a5-4027-ae59-51e8f95c2a1f)
![firebase2](https://github.com/jsseng/jigsaw/assets/156022154/f69a16a8-d736-4afd-a4d9-34920f98d212)
