### ISSUE TITLE
All pieces should snap into the nearest grid location

### ISSUE THREAD

**Issue by jsseng** [jsseng/jigsaw#22]
If the piece is incorrect, a border should highlight the piece.  Correctly placed pieces should stay locked in place.

**Comment by jsseng** [comment]
I merged the code and it was working.  One problem is that it highlights 2 neighboring boxes if the piece is positioned just right.  Could you modify it to highlight just 1 box?

**Comment by LambNNot** [comment]
I have made the corrections and refactored some of the code implementing a more intuitive use of signals
