### ISSUE TITLE
Research the Godot Firebase plugin

### ISSUE THREAD

**Issue by jsseng** [jsseng/jigsaw#26]

**Comment by KailuanLiu** [comment]
https://www.youtube.com/watch?v=7ehE4IdSP5s&ab_channel=BoonMakesGames

**Comment by jsseng** [comment]
Look into the Firebase maximum image file size limit.

**Comment by jsseng** [comment]
Next step is to record (in the database) when the user last used the application and then display that the next time the application is run.

**Comment by KailuanLiu** [comment]
Discussion post regarding firebase image sizing
- https://stackoverflow.com/questions/38395790/firebase-storage-limit-size-of-Image-that-users-upload-to-firebase-storage 
Sample tutorial of how to restore a timestamp
- https://github.com/GodotNuts/GodotFirebase/issues/143
GDScript on how to update Firebase database 
- https://github.com/GodotNuts/GodotFirebase/wiki/Firestore#add-a-document
