### ISSUE TITLE
fix image path when exporting the application

### ISSUE THREAD

**Issue by jsseng** [jsseng/jigsaw#31]
When I try to export the application, it does not seem to load the images.  Maybe there is a problem with the path

**Comment by stephenlin801** [comment]
I changed how the files were loaded in so that it would export and display the images properly. I'm not sure about other machines but I was able to export it properly on mine.

**Comment by stephenlin801** [comment]
The fixed code is in the UI branch.

**Comment by LambNNot** [comment]
Okay I'll test it on my end

**Comment by stephenlin801** [comment]
Great, let me know if there are any issues.
